Mellanox/bfscripts

bfinst, bfrec, bfsbkeys, bfscripts.spec.rpkg, bfvcheck, bfvcheck.service
In addition, modify any scripts that check the existence
of a file in /opt/mlnx/scripts to just check for the file's on
the current PATH.
=> Move install directory of bfscripts to /usr/bin

bfscripts.spec.rpkg, man/bfauxpwr.8, man/bfbootmgr.8, man/bfcfg.8, man/bfcpu-freq.8, man/bfdracut.8, man/bffamily.8, man/bfinst.8, man/bfpart.8, man/bfpxe.8, man/bfrec.8, man/bfsbkeys.8, man/bfvcheck.8, man/bfver.8, man/mlx-mkbfb.1
- Add all man pages
- Add bfauxpwr to fedora spec file
=> Add man pages for each script

README.md, debian/mlxbf-scripts.install, man/bfrshlog.8, mlxbf-bfscripts.spec, mlxbf-bfscripts.spec.rpkg
This commit has the follow-up changes for bfrshlog to add it into
installing script and also creates man page for it.
=> Follow-up changes for the bfrshlog script

mlxbf-bfscripts.spec, mlxbf-bfscripts.spec.rpkg
There are no python 2 scripts in this package anymore, so just
change to python3 dependency.
=> Change python dependency to python3

bffamily
Add Camelantis, OVH and Aztlan as well as new BlueSphere OPNs
=> Add new viper boards

bffamily
=> Support El-Dorado 16G in bffamily

bfpxe
Allow a mac address to be passed to bfpxe and provision from that interface.
=> Draft: Pass in bfmac to bfpxe

bfpxe
Looks like #117 was merged prematurely @sl-mlx
=> Fix missing brackets

debian/mlxbf-scripts.install, mlxbf-bfscripts.spec, mlxbf-bfscripts.spec.rpkg
Adding the bfgrubcheck script to the deb and rpm packages.
=> add bfgrubcheck to rpm and deb packages

man/bfpxe.8
Co-authored-by: Liming Sun <limings@nvidia.com>
=> bfpxe: update man page

bfrec, bfsbverify
This pull request provides the following changes:
- Fix for 'bfsbverify' command
- Enhancement of 'bfrec' command
=> commits to enhance 'bfrec' command to verify BFB signature

bfrec
=> bfrec: request user confirmation for debug boot image update

bfcfg
=> Create VLAN 4040 if OOB boot entry is configured

bfsbdump
THis commit adds ECID dump which is supported in BlueField-3.
=> bfsbdump: add ECID dump

bfvcheck
Removed syntax error
RM #3735957
=> bfvcheck: unexpected print error

bffamily
=> Add HPE OPNs to bffamily

bfcfg
=> bfcfg: dump OsArgs from BFCF ACPI table

bfcfg
This commit revert 2c8a65c6 e237076b from bluefield-rel/3.9.x.
=> Revert 2c8a65c6 e237076b

man/mlx-mkbfb.1, mlx-mkbfb
=> mlx-mkbfb: add -c option to check BFB

bfcfg
Add support to set and read I2C3 enable status (similar to I2C0).
RM #3965140
=> Add I2C3 enable support

bfcfg
=> bfcfg: add SYS_DISABLE_I2C1 system config parameter

bfcfg
Add boot watchdog configuration to bfcfg dump.
RM #4106141
=> Dump boot watchdog config

bfcfg
=> bfcfg: display profile root key and profile CA certificate info

bfcfg
=> bfcfg: fix typo in misc_dump_profile_key_and_certs() routine

bfcfg, bfup
This commit passes some OS info to UEFI for debugging purpose. For now only the log_buf and log_buf_len are added.
RM #3969792
=> Pass OS info to UEFI

bfcfg
=> Update bfcfg to support SYS_ENABLE_BMC_WAIT

bfhcafw, bfver
This is simply a cherry-pick of the two commits for more gracefully handling non-root users from `master` into the 4.9.x branch.
=> Handle non-root users more gracefully (4.9.x)

mlx-mkbfb
=> mlx-mkbfb: Reserve ID for golden images (#261)

bfcpu-freq
Update bfcpu-freq with new cppc approach
RM #[4461074](https://redmine.mellanox.com/issues/4461074)
=> Update bfcpu freq

bfcfg
=> Add bmc wait

bffamily
0KK4NR, 06CMW1 based on 9009D3D400ENHA0
0WJ9T5, 0HFWRM based on 9009D3B600CVAA
RM #4540685
=> Add new custom OPNs to bffamily

bfcfg
Use new scheme for bfcfg_version and bump PCP_VERION.
This is to amend PR https://github.com/Mellanox/bfscripts/pull/274
RM #[4517898](https://redmine.mellanox.com/issues/4517898)
=> Amend commit 0ec9f64 for version info

bfcfg
=> Add LLC_READ_ALLOC config parameter to bfcfg
