Mellanox/bfscripts

- bfinst
The current bfinst uses capsule by default to upgrade the eMMC
boot partition in next boot. It relies on the old boot images
to be working and compatible with latest FW which might have
been upgraded, or else the upgrade will fail. This commit tries
to update the boot partition directly. The capsule update is
preserved in case it's needed later for secure boot or the boot
partition is locked.
> Update eMMC boot partition directly in bfinst

- bfinst
This commit changes to use mlxbf-bootctl to update boot
partition when calling bfrec in bfinst. Previously
it uses capsule upgrade which relies on the old boot
images to be working and compatible with latest FW.
> Use mlxbf-bootctl to update boot partition in bfinst

- bfcpu-freq
The padfrequency should be 156.25Mhz for BF2.
The core_od bites are 3:0 instead of 4:1
> Fix bfcpu-freq script

- README.md
- bfauxpwr
In OCP 3.0 card, the GPIO driver receives indication from NIC FW
and sends a netlink message. Configure the ACPI daemon to handle
this event by powering up/down all secondary cores based on the
current state of the GPIO pin.
Also disable the power button event handler in systemd.
> Add bfauxpwr script to handle OCP 3.0 AUX power mode

- bfauxpwr
bfauxpwr adds the powercontrol script as an ACPI action.
The Shell script does not work the same way on Yocto and
Ubuntu. Switch to bash to fix this.
> Change powercontrol shell script to bash

- bfcpu-freq
* Fix bfcpu-freq script
The padfrequency should be 156.25Mhz for BF2.
The core_od bites are 3:0 instead of 4:1
* Update bfcpu-freq
> Fix bfcpu-freq script (#18)

- bfpart
A previous issue existed where the DISK{}_PART{}_TYPE value
was being assigned the partition UUID after the first call of the
bcfg() function. However, the partition name value was then lost
and could not be accessed during the second call of this function.
In order to ensure that the part_type value used for partition UUID
assignment is a name, and not a UUID, a conditional structure was
implemented to catch this and switch the UUID back to a name before
entering the partition UUID assignment block.
RM: #2164870
> Fix eMMC partition naming and UUID assignment

- bfcfg
This commit fixes the command to get MAC address for BF2 cards.
It also checks the possible 'NA' result when MAC is not set.
> bfcfg: Fix getting the MAC address for BF2 cards

- bfinst
It was found that some configuration created by bfcfg was overwriteen
by bfinst. This commit calls bfcfg again to avoid such issue.
> bfinst: call bfrec after installation

- .gitignore
- Makefile
- bfscripts.spec
Some systems do not have up to date versions of rpkg available,
so add a generated spec file and a Makefile that can build SRPMs
from the generated spec file.
> Add spec file and Makefile to build SRPM

- Makefile
Adding the Makefile has caused debhelper to automatically attempt to
use it for builds. Move the srpm build to its own target, and fix
the clean target so it will run even if there's nothing to clean.
> Fix debian build

- bfrec
bfrec has an issue running under Ubuntu's interpreter, dash. For now,
switch the interpreter to bash.
> bfrec: Run under bash to fix on Ubuntu

- README.md
- bfcfg
- bfhcafw
- man/bfhcafw.8
In order to improve compatability, remove the direct use of the
proprietary "flint" executable, preferring mstflint where available.
Also, do not depend on mst for the PCI conf device.
> Remove direct references to flint

- bfcfg
This commit fixes two issues.
1. There is a typo when building the PXE MAC address. MAC address
is 6 bytes, so the full length without the ':' should be 12 instead
of 8. This issue will cause incorrect result for MAC address starting
with 0.
2. The disk boot entries should preserve the original order. So if
PXE boot fails, it could continue to boot from eMMC or other storage
device as expected.
> bfcfg: Fix disk boot entry order and PXE entry MAC address

- bfinst
This commit removes the extra argument "--bootctl" when calling
bfrec because bfrec has been improved to select the default
boot record update method automatically in order to support UEFI
secure-boot.
> bfrec: Remove the argument when calling bfrec

- bfrshlog
This commit adds the bfrshlog wrapper script for rshim logging.
Usage: bfrshlog <log messages>
> Add bfrshlog script

- bfcfg
The MAC address setting uses printf which seems not robust
enough and could fail. This commit fixes it by using a temp
file then copying it into the EFI variable.
> bfcfg: Fix the MAC address configuration

- bfinst
This commit increases the rootfs tarball decompression waiting time
from 600 seconds to 900 seconds due to increased rootfs size.
> Increase the rootfs tarball decompression waiting time

- bfvcheck.service
EMC has requested for the BF to report that
linux has completed booting via the rshim
Their BMC is the rshim host.
To do that, bfrshlog will be called from the
bfvcheck script to report that the linux is up
since the bfvcheck service is scheduled to run
once the login prompt appears.
RM #2326964
> Add informative message for linux being up

- bfvcheck.service
Customer has requested for the BF to report that
linux has completed booting via the rshim
Their BMC is the rshim host.
To do that, bfrshlog will be called from the
bfvcheck.service to report that linux is up
since the bfvcheck service is scheduled to run
once the login prompt appears.
RM #2326964
Co-authored-by: Asmaa Mnebhi <asmaa@nvidia.com>
> Add informative message for linux being up (#77)

- bffamily
- bfhcafw
- man/bfhcafw.8
- Run references to ConnectX through bfhcafw
- Add new "bus" command to bfhcafw that just prints correct PCI bus
number for current platform
Fixes "can't find flint" error on some distributions.
> Abstract ConnectX references in bffamily

- debian/mlxbf-scripts.install
- mlx-uefi.quirk
- mlxbf-bfscripts.spec
- mlxbf-bfscripts.spec.rpkg
Temporary tweak to enable fwupd support on BF hardware until quirk
can be added to fwupd project
> Add mlx-uefi.quirk file for fwupd

- bfcfg
Previously the NIC port MAC was calculated from BaseMac which is not
accurate because different boards have different formula. This commit
fixes it by using the sysfs instead. By the time the script is called,
the mlx5_core driver should have been loaded and the MAC address should
be available in sysfs already.
> bfcfg: Get NIC port MAC from sysfs instead of BaseMac

- bfinst
Grub EFI is built along with the Yocto file system images
and a grub EFI binary is being installed into the full file
system image. As the binary might be signed then use it
instead of doing a new installation of grub.
> bfinst: use existing grubaa64.efi binary if present

- bfcfg
The current logic in 'bfcfg' will log a warning if only one
of the two MFG parameters (OOB_MAC and OPN_STR) are specified.
In this case, there is no error displayed to the user, only to
the 'bfcfg' log.  This patch adds logic to display an error
message to the user if only one MFG parameter is specified.
> bfcfg: display error if only one MFG parameter specified

- bfrshlog
This commit enhances bfrshlog to display the current rshim logging
buffer if no argument is provided.
> bfrshlog: display the logging buffer if no argument

- bffamily
On Dell Camelantis, bffamily fails because bfhcafw fails with the
following error:
root@localhost:~# bfhcafw flint dc
-E- Failed dumping Fw Configuration : Unsupported operation under Secure FW
Replace that command with mlxfwmanager to retrieve the OPN.
Also, replace the space in "Dell Camelantis" with "-".
> Fix the bffamily script

- bfinst
- bfrec
- man/bfrec.8
Allow the user to choose whether bfrec updates only one or both boot
partitions.
> bfrec: Add --policy option

- bfver
- man/bfver.8
Add --part|-p option to bfver, which allows the user to specify which
boot partitions bfver checks for versions.
> bfver: Add --part option

- bfver
The trap utility does not accept SIGTERM/SIGINT under the Ubuntu/Debian
shell, dash. This causes bfvcheck to fail on startup. Change
SIGTERM and SIGINT to TERM and INT.
> bfver: Remove SIG prefix for trap

- mlx-mkbfb
Move psc-fw before the BL2 image for BL2 decryption. It also help
avoid potential conflict between the image loading of BL2 and PSC
BL1/FW.
> Move psc-fw before BL2

- README.md
- bfacpievt
- bffamily
- man/bfacpievt.8
Remove all code related to GPIO 7 reset from bfacpievt.
Add new OPNs to bffamily:
1) El Dorado: MBF2M355A
2) Camelantis: MBF2H532C
> Cleanup bfacpievt script

- bfcfg
Previously the get_hca_p0_mac funciton walks through all interfaces
by filtering the devid, which is not efficient with certain config
where multiple virtual interfaces are created with the same devid.
This commit checks the 3-byte OUI of the BASE-MAC to avoid such
problem.
> Fix the get_hca_p0_mac function in bfcfg

- mlx-mkbfb
As the capsule is expected to be read before the boot parameters
(boot-desc, boot-path and boot-args), then generate the capsule
first. This will prevent the boot parameters from being overwritten
during UEFI BDS phase, if capsule update is enabled.
> mlx-mkbfb: append capsule prior to appending boot parameters

- bfhcafw
In secure boot mode, using bffamily results in the following errors:
[  29.163873] Lockdown: mstmcra: direct PCI access is restricted; see man kernel_lockdown.7
This is because bffamily calls bfhcafw which calls mstmcra.
UEFI secure boot enables the kernel lockdown feature which blocks access by mstmcra.
So always check for the mcra command first, before mstmcra
and flint first before mstflint.
RM #2799334
> bfhcafw: fix call to mcra and flint in secure boot

- bfinst
This small patch adds logic to verify that fspath,
i.e. argument to "--fullfs", exists before attempting
to repartition the storage device.
> bfinst: exit if fspath does not exist

- bfpxe
- mlx-mkbfb
This commit reserves an image ID for PSC applications, which will
be loaded into secure DRAM by ATF BL2.
> mlx-mkbfb: Reserve an image ID for PSC applications

- bfpxe
* 60 seconds is not sufficient in some cases (slow oob_net0 connection on Camelon?)
Signed-off-by: Yurii Shestakov <yuriis@nvidia.com>
> bfpxe: increase wget $bfks timeout to 180 seconds

- man/mlx-mkbfb.1
- mlx-mkbfb
Add an option that allows for the filtering of 
BFBs for specific hardware versions. This mode
will remove all images from a BFB not needed
to boot the specified BlueField revision, resulting
in smaller images.
> mlx-mkbfb: Add --filter option

- bfrec
Currently bfrec sends its error messages to stdout. This means that
"bfrec 2>/dev/null" will not supress error messages as expected, which
can produce false positive error messages in certain install scripts.
Send errors to stderr instead.
> bfrec: Send error messages to stderr

- bfcfg
- bfrshlog
Upstream mlxbf-bootctl driver (MLNXBF04:00) creates the sysfs files at device level. This commit checks <sysfs>/MLNXBF04:00/driver/rsh_log first, then <sysfs>/MLNXBF04:00/rsh_log if not found.
> bfrshlog: Support upstream mlxbf-bootctl driver

- bfcfg
The current 'bfcfg -d' command truncates the dhcp_class_id when it is longer than 12 characters. This commit fixes it by using xxd since the maximum length of dhcp_class_id has been increased from 9 to 32 in UEFI.
> bfcfg: Support dumping of long dhcp_class_id

- README.md
- bfsbverify
- debian/mlxbf-scripts.install
- man/bfsbverify.8
- mlxbf-bfscripts.spec
- mlxbf-bfscripts.spec.rpkg
This commit provides a new script that reads the BFB from file or from eMMC boot partition and verifies its Root-of-Trust public key and Chain-of-Trust certificates.
The script requires a standard shell/bash environment with 'openssl', 'mlx-mkbfb', 'mlxbf-bootctl' and other basic shell commands.
RM #3197761
Usage:
```
bfsbverify   [-h|--help]
[-k|--rotpk ROTPK]
[-v|--version VERSION]
[-s|--skip-cot]
[-b|--bfb BFB]
[-d|--dev DEV]
Verify the BFB certificate chain. To learn about supported options
run the command with '--help'.
Manadatory arguments:
-b|--bfb                The input BFB file to verify.
-d|--dev                The eMMC boot partition device to verify.
(e.g., /dev/mmcblk0boot0, /dev/mmcblk0boot1)
'-b|--bfb' and '-d|--dev' cannot be combined together.
Optional argument …
```
> bfsbverify: add script to verify the RoTPK/CoT of the BFB

- bfcfg
This commit removes the 'warning: command substitution: ignored null byte in input' message on Ubuntu by skipping the first 4 bytes when displaying the PXE_DHCP_CLASS_ID UEFI variable. The first 4 bytes are fixed and not related to the content itself.
> bfcfg: removing warning

- bfsbverify
In BlueField-3 there are 4 pre-generated ROTPKs; so far only one key is used for signing. When calling 'bfsbverify' to verify the ROTPK of version 2 (BlueField-3) binaries, 'compare_rotpk_mfg' returns when comparing the input key to the second ROTPK key which is expected. Indeed, the first comparison succeeded as the input key matches the first ROTPK. But this is not true for the remaining ROTPKs. Thus update the logic to return as soon as matching key is found.
Also update the short options configuration when parsing the script arguments.
> bfsbverify: fix bogus logic 'compare_rotpk_mfg' function

- mlx-mkbfb
BF3 requires some extra data in the boot partition to read in order to terminate the eMMC FSM when booting from eMMC. This change is added for this purpose.
> Reserve one image id for padding

- mlx-mkbfb
This commit adjusts the padding image order to behind the boot configurations, so it can be the last image in default.bfb
> Adjust the padding image order

- bfcpu-freq
This script can be used to measure P0 and P1 clock states.
> bfcpu-freq: Add BF3 support

- bffamily
Currently, we use flint to read the PN. But looks like this info is not accurate, and reflects an internal PN from the FW INI, and not the official PN. So reading the PN info from the VPD should be more reliable.
Sample output using the current method:
root@localhost:/home/ubuntu# flint -d /dev/mst/mt41692_pciconf0 q full
Part Number:           900-9D3B4-00EN-E_QP_Ax
(The PN found above is not an official OPN but an internal one)
Using the VPD instead:
root@localhost:/home/ubuntu# mlxvpd -d /dev/mst/mt41692_pciconf0
PN             Part Number             900-9D3B4-00EN-EAB
(This is the correct OPN to be used)
RM #3334340
> bffamily: Read OPN using mlxvpd instead of flint

- bfhcafw
- bfvcheck
A previous fix broke bfhcafw's search mechanism for older distributions. Fix this. Also, add a more accurate error message for cases where recommended firmware cannot be determined.
> bfhcafw, bfvcheck: Fix firmware searching

- bfver
- man/bfver.8
- Support build ID, use it to print BSP version normally found on filenames
- Print DOCA version file if it's present.
- Allow printing BSP versions from any file, not just /dev/mmcblk0boot*
> bfver: BSP version updates

- README.md
- bfsbdump
- debian/mlxbf-scripts.install
- man/bfsbdump.8
- mlxbf-bfscripts.spec
- mlxbf-bfscripts.spec.rpkg
This script relies on 'BfSbStatus' EFI variable to read and print information about the life cycle, the crypto config, the secure boot, non volatile counters and other DOT info.
RM #3353907
> add 'bfsbdump' to dump secure boot status information

- mlx-mkbfb
Supports insertion of the DOT Auth Cert for debug BFBs. Version 1 of the cert to be used for BF2
Version 2 of the cert to be used for BF3
Tested offline via the cmdline:
./mlx-mkbfb --dot-auth-cert-v1 authcert-example.der default.bfb debug.bfb
./mlx-mkbfb --dot-auth-cert-v2 authcert-example.der default.bfb debug.bfb
RM #3322861
> bfscripts: Modify mlx-mkbfb to support new DOT Auth Certificate

- README.md
- bfstart
- bfvcheck.service
- debian/mlxbf-scripts.install
- man/bfstart.8
- mlxbf-bfscripts.spec
- mlxbf-bfscripts.spec.rpkg
ARM needs to indicate that linux is up to the NIC via fw_gpio[16] for the following reasons:
1) mlxfwreset sync 1 to initiate full chip reset on BF3. When the system is in low power state (due to panic for example), the NIC needs an indicator to trigger the DPU reset.
2) Some customers such as Baidu and CTC also might need this indicator since their x86 host boots much faster than the DPU. Their x86 host however, needs to wait for the DPU to be fully booted due to its dependency on virtio. This design has not been approved yet but it is something to take into account.
Setting the ARM boot state in gpio-mlxbf2.c and gpio-mlxbf3.c is not a good solution because:
- it will unlikely be accepted by the upstream community
- it will allow userspace to have access to the concerned GPIOs via sysfs …
> Support setting ARM boot state to OS up in GPIO

- bfrec
Use 'lsblk' command to look for the EFI System Partition device block instead of using the default '/dev/mmcblk0p1'. Indeed, the ESP can be installed within an NVMe disk partition, it is not always expected to be within an eMMC disk partition 1.
> bfrec: lookup for ESP disk partition

- bfrec
This fix adds checking for python3 to avoid failure in bfsbverify.
RM #3457900
> bfrec: add checking for python3

- bfcfg
MFG Extension partition can be configured using the following variables:
* MFG_SYS_MFR
* MFG_SYS_PDN
* MFG_SYS_VER
* MFG_BSB_MFR
* MFG_BSB_PDN
* MFG_BSB_VER
* MFG_BSB_SN
Depends on:
https://bu-gerrit2.mtbu.labs.mlnx/#/c/ezchip/+/11287/ 
https://bu-gerrit2.mtbu.labs.mlnx/#/c/edk2/+/11288/ 
https://bu-gerrit2.mtbu.labs.mlnx/#/c/atf/+/11289/
RM #3455056
> Extend bfcfg to support configuration of MFG Extension partition

- bfsbverify
Fixes: 92b0c1c ("bfsbverify: add script to verify the RoTPK/CoT of the BFB")
> bfsbverify: fix BL32 image version and content certificate PK OID

- bfcfg
This commit has changes to return error code when CX5 MAC
> bfcfg: Return error code for invalid MAC

- bfver
- debian/control
- mlxbf-bfscripts.spec
This commit fixes UEFI version for compressed image which is introduced in BSP 2.5
> bfver: Fix UEFI version for compressed image

- bfvcheck
This commit fixes the version fetching from default.bfb using the same bfver script.
> bfvcheck: Fix the version fetching from default.bfb

- bfsbdump
Initially 'BfSbStatus' EFI variable is created using the EFI Global Variable GUID which is not platform specific and might cause confusions among variables managed by common drivers and variables managed by the platform drivers. Thus, a platform GUID has been introduced and as a result the EFI Variable file name in efivar file system must match the current GUID used to create the variable.
This commit also re-implements 'GetPlatformName()' function to run on LiveFish devices.
> bfsbdump: add new filename of 'BfSbStatus' EFI variable

- bfrec
Old versions of 'fdisk' don't display the device full name of the EFI System Partition thus the output cannot be parsed given the current logic. Thus substitute 'fdisk' command with 'blkid'. The block devices listed by 'blkid' are filtered out using the LABEL field. It is expected that EFI System Partition would show either "system-boot" or "EFI*".
These changes implemented in 'bfrec' should be compatible accross distirbutions.
RM #3693653
> bfrec: use 'blkid' instead of 'fdisk' to display ESP devices

- bfcfg
The 'bfcfg' command is used to program the MFG and configure the UEFI settings and other parameters. As of today the MFG is programed through sysfs interfaces. Once programed, the data is SW protected against writes and can only be reset through UEFI. Hence a method is then required to re-program the MFG data which can be safely initiated by 'bcfg'.
For this puprose, an EFI Capsule is generated and may contain MFG data, MFG extension data and other configuration dependencies such as the UEFI system attributes and the Redfish parameters.
This commit implements the following:
- Redfish parameters configuration support.
- 4KB Binary generation to contain MFG data and MFG extension data, optionally BfSysCfg and BfRedfish EFI variables data.
- Capsule generation using the configuration binary. …
> bfcfg: add capsule support for MFG programing

- README.md
- bftraining_results
- debian/install
- man/bftraining_results.8
- mlxbf-bfscripts.spec
Look for devices with HID MLNXBF3B in the SSDT and extract the DDR5 training results.  There should be one device entry for each of the four possible DDR channels.
RM #3693559
> Add script to print DDR training parameters

- bfcfg
The initramfs of the self-install BFB might be missing commands and modules needed to generate the EFI capsule; so push the MFG settings to the payload of a pregenerated EFI capsule file.
RM #3728948
> bfcfg: support pre-built EFI capsule for MFG programming

- bfvcheck
Added more detailed prints for running and loaded FWs. 
As well, if there is loaded FW exit code is 1.
RM #3634475
> bfvcheck: reporting wrong FW version as Installed version

- bfcfg
- bfsbverify
When 'bfcfg' cannot be executed from Arm operating system, an alternative would be to run the command on external host to convert the config file to a binary format.
Example of usage:
$ bfcfg -c bf.cfg
16+0 records in
16+0 records out
4096 bytes (4.1 kB) copied, 0.000513951 s, 8.0 MB/s
bfcfg: configuration blob written to bf.cfg.bin
The output binary filename consist of the input filename with a the extension '.bin'. In this example, the output filename is 'bf.cfg.bin'.
The binary file can be used to create an EFI capsule. The capsule file can be appended to a BFB file and applied from external host. Once applied, the configuration is processed by the platform firmware. As of now only MFG configuration is supported.
> bfcfg: add option to convert config to binary

- bfup
This is required for the older versions of the bfb-install script to exit when the BFB installation finished and the DPU is up after the first boot. Without this bfb-install will not finish.
> bfup: Adding "DPU is ready" to the rshim log

- bfcfg
This commit fixes a warning message when adding VLAN on OOB interface where it already exists. Since it's a fixed VLAN ID, it doesn't cause any functionality issue rather than the warning message. The fix is to clear the 'i' attribute before overwriting existing file.
RM #3755688
> bfcfg: fix a warning when creating VLAN on OOB interface

- bfsbverify
The 'bfsbverify' command relies on a common temporary folder under /tmp/bfbtmp; when user A executes the command and the temporary folder is left undeleted (because of a failure or because the command execution is interrupted), then user B would fail to execute the command because the bfsbverify won't have the permissions to cleanup the temp directory initially created by user A. Thus address the issue by creating separate temporary foders per user context.
RM #3766115
> bfsbverify: create temporary folder per user

- bfver
When '-p0,1' is specified in 'bfver' command line the version is read from both boot partitions. Thus, print_path_vers() is called against the primary and secondary boot partitions. As a result, print_bfb_file_vers() is called twice and fail to create the temp folder because it already exists, i.e., previously created during the first call. To address the issue, cleanup the temp files at the end of print_bfb_file_vers() routine, so that next call won't fail to create the temp folder.
> bfver: cleanup temp files in print_bfb_file_vers()

- bfcfg
Add new configuration parameter to update the mode, i.e., select either "DPU mode" or "NIC mode". The mode update is initiated by bfcfg, is processed by UEFI Capsule updates and is applied by the UNDI driver upon power cycle.
This commit also fixes the binary path when the config file is converted to EFI capsule.
RM #3800864
> bfcfg: support MFG_PLAT_MODE to switch BlueField modes

- bfsbverify
The error "trap: SIGHUP: bad trap" is returned when 'bfsbverify' command is executed on Ubuntu shell; 'sh' is being linked to 'dash' and the 'SIG' prefix causes an error when executing 'trap' command line. Thus omit the prefix 'SIG' from signals listed in the 'trap' command line.
> bfsbverify: omit 'SIG' prefix from signals listed in 'trap' command line

- bfvcheck
This is to support Secure Boot when MFT is not installed.
RM #3819821
> bfvcheck: Use mstflint if mstflint_access module is loaded

- README.md
- bfperf_bf3_pmc
- debian/install
- man/bfperf_bf3_pmc.8
- mlxbf-bfscripts.spec
- mlxbf-bfscripts.spec.rpkg
The python source is provided by the Perf team and is added to bfscripts as a python executable. The tool utilises the PMC driver to provide DDR performance metrics.
RM #3771106
> Add bfperf_bf3_pmc tool to bfscripts

- bfacpievt
- bfdracut
- bfinst
The following scripts are deprecated and will no longer be supported:
- bfinst
- bfdracut
- bfacpievt
These scripts will eventually be removed so logs have been added to warn users in advance. Verified by running scripts and making sure warning log is visible first.
RM #3830034
> Add warning logs to notify script deprecation

- bfcfg
When displaying MFG information with the dump option, the bfcfg command can display unprintable characters that garble the display.
RM #3842885
> bfcfg -d command displays unprintable "garbage" characters

- bffamily
Add Zhora as a new family type because of its unique OPN and configuration.
RM #3821681
> Add Zhora OPN to bffamily

- bfcfg
The 'BfCfgOobMac' EFI variable might contain incorrect value because of a bug in the UEFI logic intented to read the OOB MAC from the MFG.
RM #3932095
> bfcfg: revert reading OOB MAC from sysfs

- bfcfg
A new EFI variable has been added to hold the BF Bundle version string. Add support to bfcfg to dump the variable contents and allow for writing new values with an environment variable.
RM #3884433
> Add support for new 'BfBundleVer' EFI variable

- bfrec
- mlx-mkbfb
In NIC mode, a bfb image could be pushed for runtime upgrade. This BFB contains Image, Initramfs and the upgrade image, while Image/Initramfs are used by NIC mode to boot into Linux and the upgrade image are used by both NIC mode and DPU mode for upgrade, thus it needs to be the last image.
RM #3936308
> Reserve image id for runtime upgrade

- bfver
Recent changes to our bl33 binary have resulted in some data
getting rearranged in the binary's data section. The bfver script
uses the Linux "strings" utility to parse the "BId" string from the
raw binary and, depending on the data that is next to that string in the
binary, can sometimes include unexpected bytes as part of the
located string.
For example, the following shows how there is an "a" character
prepended before the expected build ID string:
```
root@bu-lab102:~/cbabroski/tmp# strings -el dump-bl33-v0
aBId13164
...
```
And this results in the BSP version displayed by bfver to have a
corrupted build ID:
```
svc-soc-ver@bu-lab40v-oob:~$ sudo bfver
...
BlueField BSP version: 4.8.0.aBId13156
```
The fix is to update the sed regex used to cut out the build ID number
which should …
> Parse out unintended bytes in build ID string

- bfhcafw
- bfrec
- bfsbdump
Platform type is found by parsing through SSDT tables for respective strings. Using hexdump utility is prone to be ineffective as SSDT tables are updated over time and the string is not placed on the same line for grep utility to succeed. For example, below is the output from hexdump and we can observe "MLNXBF33" string is spread over two lines and therefore grep will fail: 
|.M.GPI1._HID.MLN| 
|XBF33.._UID.._CC|
RM #3951579
> Update search method for platform type

- bfcfg
This commit implements the following changes:
* Update control flags for Arm settings; add flags to manage UEFI secure boot settings and UEFI password settings.
* Add extra Arm UEFI system attributes, i.e., SYS_ENABLE_I2C3 and SYS_ENABLE_FORCE_BOOT_RETRY.
* Support Arm UEFI Secure Boot PCP; to enroll UEFI secure boot certificate files.
RM #4049059
RM #4049061
Fixes: c134069 ("bfcfg: enhance 'cfg2bin' command and add 'bin2cfg' command")
> bfcfg: support additional UEFI settings

- bfcfg
Add missing UEFI config options to bfcfg dump so the bfcfg dump output can be used to compare defaults across releases. A dump level option has also been added to bfcfg to increase the amount of information dumped like the boot order and public keys/certificates used for secure boot.
RM #3969767
> Add missing UEFI config options to bfcfg dump

- bfcfg
This commit updated the SYS_L3_CACHE_PART_LEVEL from two bytes to one byte. Also updated the bfcfg version to 4.2.
RM #4093243
> bfcfg: change SYS_L3_CACHE_PART_LEVEL to one byte

- bffamily
(Backport from 4.x to 4.7.1)
A new OPN is being added and should support the same SW functionality as 8217991.
RM #4093183
> Support new Moonraker OPN

- bfcfg
* Currently when creating OOB Vlan efivar, lower-case MAC address of OOB is used for efi variable name. This is not in accordance with edk2 UEFI which uses upper-case MAC address for efi variable name.
* In order to rectify the incorrect efi variable created in previous version of this script, delete the incorrect efi variable with lower-case name during cleanup.
RM #4119852
> bfcfg: Fix creation and deletion of OOB Vlan efivar

- bfcfg
The following parameters are now supported:
* CTL_SAVE_CONFIG_FILE: when set to 'TRUE' the file encapsulating the configuration file is saved within a persistent storage.
* CTL_RESET_LANG: when set to 'True' the EFI variables for Language settings are deleted.
* BMC_DISABLE_ROOT: parameter to disable root user on DPU BMC.
* BMC_SERIAL_REDIRECT_ENABLE: parameter to redirect the serial port on the DPU BMC.
Also bump-up the PCP version to reflect changes in the parameters supported in the PCP payload.
The bfcfg command version is incremented as well.
RM #4025893
RM #4094255
> bfcfg: support additional Arm and Bmc config parameters

- bfcfg
We were reading the wrong byte offset to determine the configured boot watchdog mode.
RM #4106141
> Fix issue dumping watchdog config

- mlx-mkbfb
Implement an "info" field in mlx-mkbfb to include a dump-info-v0 file in the BFB. This file contains version information for various BFB components, enabling easier tracking and verification of BFB contents
RM #4247297
> mlx-mkbfb: Add "info" field for components version tracking

- bffamily
A new Moonraker family OPN is being added that starts with 900-9D3L. Add support to bffamily to identify this board as a "Moonraker".
RM #4298946
> Add new Moonraker OPN

- mlx-mkbfb
This commit adds NIC_FW support into BFB.
RM #4330052
> Support NIC_FW image into BFB

- bffamily
A new Moonraker family OPN is being added that starts with 900-9D3L. Add support to bffamily to identify this board as a "Moonraker".
RM #4298946
> Add new Moonraker OPN (#245)

- bfcfg
This commit adds support to enable BMC reset during next reboot by creating UEFI variable BmcUpgradeReset. To avoid re-applying /etc/bf.cfg if already exists, '-f' argument is added to specify the config file instead of using hard-coded /etc/bf.cfg.
With the changes, command "BMC_UPGRADE_RESET=1 bfcfg -f /dev/null" can be used to enable the BMC upgrade reset. It is applicable to all other configurations which can be sourced from bf.cfg.xi The '-f /dev/null' is only needed to avoid using /etc/bf.cfg if already exists.
RM #4368528
> bfcfg: Add BMC reset support during next reboot

- mlx-mkbfb
This commit breaks the loop when exacting a single image after having found it. It also ports a graceful change to hangle ctrl+C.
RM #4374856
> mlx-mkbfb: Improve the performance when extracting a single image

- bfhcafw
- bfver
The bfver and bfhcafw scripts require root privileges for certain parts of their functionalities, but the scripts do not check/enforce this. If a user tries to execute those parts of the script as a non-root user, they get an excessive amount of permission error logs that clutter the output.
This commit more gracefully handles these scenarios by adding user or permission checks for commands that do not fail quickly/gracefully.
This commit also slightly refactors bfver to use a similar err function to bfhcafw and bfvcheck for better consistency and readability.
RM #4370524
> Handle non-root users more gracefully

- bfcfg
Currently, bfcfg will print an empty value for BF_BUNDLE_VERSION if the 'BfBundleVer' EFI variable is not populated. This commit changes it so that it's only printed if the EFI variable actually exists and is populated.
RM #4391227
> Don't print BF_BUNDLE_VERSION if not present

- bfhcafw
- bfver
Commit e197cd7 added checks against the current ID to fail more gracefully for non-root users. It attempts to set the "UID" variable while checking, which is only valid in some shells - in others, "UID" is a readonly variable.
This commit changes the variable being set to "m_uid" to remove the possibility of conflicts with system variables while remaining compatibility across all POSIX-compliant shells.
RM #4395696
> Fix "UID: readonly variable" error

- bffamily
Adding new OPN SN37C16116 to be identified as a Moonraker board in bffamily.
RM #4457435
> Add support for new Moonraker OPN

- bfcfg
- bfrec
- bfver
bfver: Add support to fetch ATF and UEFI versions from capsule files.
bfcfg: Add a new debug EFI varialbe to transfer ATF and UEFI versions to UEFI.
bfrec: In uefi_capsule_update(), call bfver to fetch the ATF and UEFI versions, and call bfcfg to transfer the versions to UEFI.
> Add support to parse ATF/UEFI version from capsule file, and transfer to UEFI.

- bfcfg
The configuration version and date are required to keep track of a given configuration values. This aims to address the limitation within the DPU BMC related to the storage of the file; as of today the version is specified in the filename, however the filename is updated during the storage of the file.
The new fields are "CONFIG_VERSION" and "CONFIG_DATE", their values are pushed to the PCH header.
RM #4504856
> bfcfg: support config data version and date

- bfcfg
> bfcfg: remove newline character from the ATF and UEFI version strings.

- bfrec
fix the error message and return code when the capsule file does not
contain ATF or UEFI versions. 
Created a new function parse_and_set_capsule_versions() to hanlde the logic of
parsing the ATF and UEFI versions from the capsule file, and call bfcfg to
transfer the versions to UEFI.
RM #4516610
> bfrec update for bug fixing.

- bfrec
fix the error message and return code when the capsule file does not
contain ATF or UEFI versions.
Created a new function parse_and_set_capsule_versions() to hanlde the logic of
parsing the ATF and UEFI versions from the capsule file, and call bfcfg to
transfer the versions to UEFI.
RM #4516610
> bfrec update for bug fixing in 4.9.x.

- bfsbverify
The RSA SSA-PSS slat length is usually determined based on the hash algorithm associated with the RSA operation. Thus omit option to check the salt length '-sigopt rsa_pss_saltlen:32'.
Note that a length of 32 would support signature generated with SHA256 hash.
RM #4518312
> bfsbverify: omit fixed salt length verification for RSA SSA-PSS

- bfcfg
This PR fixes a bug in the `bfcfg` script where an undefined variable `tmpdir` was being used instead of the properly defined `TMP_DIR` variable.
The script was using `${tmpdir}` in three functions:
- `set_osinfo()`
- `set_cap_atf_version()`
- `set_cap_uefi_version()`
However, `tmpdir` was never defined in the script, while `TMP_DIR` is the actual defined temporary directory variable.
Replaced all instances of `${tmpdir}` with `${TMP_DIR}` to use the correct variable that is actually defined in the script.
- `bfcfg`: Fixed variable references in 3 functions
This fix ensures that temporary files are created in the intended directory and prevents potential runtime errors due to undefined variables.
> bfcfg: Replace undefined tmpdir with TMP_DIR variable
